// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFgBlh6Ly_5esP4E2XduCb2vc8mMs7oU8',
    appId: '1:340253680497:web:db11798ace849728c2ccd0',
    messagingSenderId: '340253680497',
    projectId: 'fir-def9e',
    authDomain: 'fir-def9e.firebaseapp.com',
    storageBucket: 'fir-def9e.firebasestorage.app',
    measurementId: 'G-GZ2QLVVLLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYU1J0tanaOZ_7RZv-vM7iWoCLoBrnZ8M',
    appId: '1:340253680497:android:5206df2d788efc19c2ccd0',
    messagingSenderId: '340253680497',
    projectId: 'fir-def9e',
    storageBucket: 'fir-def9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgHAmZVSJOf9obffuzQGt4N98qLWFbRBA',
    appId: '1:340253680497:ios:eeca41810640825bc2ccd0',
    messagingSenderId: '340253680497',
    projectId: 'fir-def9e',
    storageBucket: 'fir-def9e.firebasestorage.app',
    iosBundleId: 'com.example.delieveryPartnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgHAmZVSJOf9obffuzQGt4N98qLWFbRBA',
    appId: '1:340253680497:ios:eeca41810640825bc2ccd0',
    messagingSenderId: '340253680497',
    projectId: 'fir-def9e',
    storageBucket: 'fir-def9e.firebasestorage.app',
    iosBundleId: 'com.example.delieveryPartnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFgBlh6Ly_5esP4E2XduCb2vc8mMs7oU8',
    appId: '1:340253680497:web:36e72a5ceb0935e0c2ccd0',
    messagingSenderId: '340253680497',
    projectId: 'fir-def9e',
    authDomain: 'fir-def9e.firebaseapp.com',
    storageBucket: 'fir-def9e.firebasestorage.app',
    measurementId: 'G-1CEKN4ZD3D',
  );
}
